# Generated by Django 3.2.25 on 2025-01-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
        migrations.AlterModelManagers(
            name='seller',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='shop_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='password',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
        migrations.AddField(
            model_name='seller',
            name='founder',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
