# Generated by Django 3.2.25 on 2025-01-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_seller_founder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Catigories'},
        ),
    ]
